<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<title>session_21_asynchronous_javascripts_1</title>
</head>

<body>
	<h1 class="text-center text-primary display-4 my-5">Asynchronous Javascripts 1 - Handling Error in Asynchronous</h1>

	<script>
		// Handling Error in Asynchronous

		async function fetchData() {
			throw new Error("Network Error")
		}

		async function getData() {
			try {
				const data = await fetchData();
				console.log(data);
			} catch (error) {
				console.log("Caught Error:", error.message);
			}
		}

		getData();
	</script>

</body>

</html>